name = "clashgo-telemetry"
main = "src/worker.js"
compatibility_date = "2026-09-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "clashgo-telemetry"
database_id = "1ce4ea2b-2100-48c1-ac30-450e4ea4f689"

